version: "3.8"

services:
  db:
    image: postgres:15
    container_name: statuspage_db
    restart: always
    environment:
      POSTGRES_DB: statuspage
      POSTGRES_USER: statuspage
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statuspage"]
      interval: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6
    container_name: statuspage_redis
    restart: always
    command: redis-server --appendonly yes --databases 2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  web:
    build: .
    container_name: statuspage
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://statuspage:password@db:5432/statuspage
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key
      STATUS_PAGE_CONFIGURATION: statuspage.configuration
      ALLOWED_HOSTS: "*"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: statuspage_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
  redis_data:
